---
- name: Install Updates
  hosts: tag_Host_pritunl_vm
  gather_facts: yes
  roles:
    - role: apt
      become: yes
  tags:
    - apt


- name: Install Updates
  hosts: tag_Host_pritunl_vm
  gather_facts: yes
  roles:
    - role: systemd
      become: yes
  tags:
    - systemd
